language: node_js

node_js:
  - 13

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  # Docker Compose Install
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# Pre-testing installs
install:
  - docker-compose -f docker-compose-build.yml build --parallel
  - docker-compose up

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push edgesentry/udagram-api-user
  - docker push edgesentry/udagram-api-feed
  - docker push edgesentry/udagram-frontend
