version: "3"
services:
  udagram-api-user:
    image: edgesentry/udagram-api-user
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
  udagram-api-feed:
    image: edgesentry/udagram-api-feed
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
  udagram-frontend:
    image: edgesentry/udagram-frontend
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
